name: Lint

on: [push, pull_request]

# Cancel jobs and just run the last one
concurrency:
  group: ${{ github.head_ref }}-lint
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
          cache: true
          cache-key: flutter-3 # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze